name = "DocStringExtensions"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.9.3"

[deps]
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"

[compat]
julia = "1"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Pkg", "Test"]
